{
 "title": "Cluster 7",
 "tags": [ "ltdb" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10m",
 "panels": [
  {
   "title": "Dashboard list",
   "type": "dashlist",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Alerts list",
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  value\nFROM used_memory\nWHERE\n  $__timeFilter(event_time)\n  and cluster = 1\nORDER BY event_time"
    }
   ]
  },
  {
   "title": "--------------------------------------------------------------------------------------------",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Node distribution",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  node AS \"Server\",\n  masters,\n  slaves\nFROM distribution\nwhere cluster = 7\nORDER BY cluster, Server\n\n"
    }
   ]
  },
  {
   "title": "Configures",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  feature as \"Feature\",\n  value as \"Value\",\n  description as \"Description\"\nFROM ltdb.configs\nWHERE cluster = 7\nORDER BY event_time desc\nlimit 4\n\n"
    }
   ]
  },
  {
   "title": "--------------------------------------------------------------------------------------------",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Used memories",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  value\nFROM used_memory\nWHERE\n  $__timeFilter(event_time)\n  and cluster = 7\nORDER BY event_time"
    }
   ]
  },
  {
   "title": "Top 10 Used memories of all redis-servers",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  value/1024/1024\nFROM used_memory\nWHERE\n  $__timeFilter(event_time)\n  and cluster = 7\nORDER BY value desc"
    }
   ]
  },
  {
   "title": "--------------------------------------------------------------------------------------------",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "In-memory data keys ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  value\nFROM datakeys\nWHERE\n  $__timeFilter(event_time)\n  and cluster = 7\nORDER BY event_time"
    }
   ]
  },
  {
   "title": "Top 10 In-memory data keys of all redis-servers",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  value\nFROM datakeys\nWHERE\n  $__timeFilter(event_time)\n  and cluster = 7"
    }
   ]
  },
  {
   "title": "--------------------------------------------------------------------------------------------",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Partitions ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  value\nFROM partitions\nWHERE\n  $__timeFilter(event_time)\n  and cluster = 7\nORDER BY event_time"
    }
   ]
  },
  {
   "title": "Top 10 Partitions of all redis-servers",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  value\nFROM partitions\nWHERE\n  $__timeFilter(event_time)\n  and cluster = 7\n"
    }
   ]
  },
  {
   "title": "--------------------------------------------------------------------------------------------",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Evictions ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  value\nFROM evictions\nWHERE\n  $__timeFilter(event_time)\n  and cluster = 7\nORDER BY event_time"
    }
   ]
  },
  {
   "title": "Top 10 Evictions of all redis-servers",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  value\nFROM evictions\nWHERE\n  $__timeFilter(event_time)\n  and cluster = 7\nORDER BY value desc"
    }
   ]
  },
  {
   "title": "--------------------------------------------------------------------------------------------",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Storages ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  value\nFROM storages\nWHERE\n  $__timeFilter(event_time)\n  and cluster = 7\nORDER BY event_time"
    }
   ]
  },
  {
   "title": "Top 10 Storages of all redis-servers(MB)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  value/1024/1024\nFROM storages\nWHERE\n  $__timeFilter(event_time)\n  and cluster = 7\n\n"
    }
   ]
  }
 ]
}