{
 "title": "Server Status",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Dashboard list",
   "type": "dashlist",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "---------------------------------------------------------------------------------------",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Alerts list",
   "type": "alertlist",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  value\nFROM used_memory\nWHERE\n  $__timeFilter(event_time)\n  and cluster = 1\nORDER BY event_time"
    }
   ]
  },
  {
   "title": "---------------------------------------------------------------------------------------",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Server CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  event_time AS \"time\",\n  node AS metric,\n  Used\nFROM server_cpu\nWHERE\n  $__timeFilter(event_time)\nORDER BY event_time"
    }
   ]
  },
  {
   "title": "Top 10 Server CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  event_time AS \"time\",\n  node AS metric,\n  Used\nFROM server_cpu\nWHERE\n  $__timeFilter(event_time)\nORDER BY event_time"
    }
   ]
  },
  {
   "title": "---------------------------------------------------------------------------------------",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Server memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  Total,\n  Used\nFROM server_memory\nWHERE\n  $__timeFilter(event_time)\nORDER BY event_time"
    }
   ]
  },
  {
   "title": "Top 10 Used Server memory(MB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  node AS metric,\n  Used/1024/1024 as \"Used(MB)\"\nFROM server_memory\nWHERE\n  $__timeFilter(event_time)\n\n"
    }
   ]
  },
  {
   "title": "---------------------------------------------------------------------------------------",
   "type": "logs",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Server disk(Used)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  concat(node , disk) AS metric,\n  Used\nFROM server_disk\nWHERE\n  $__timeFilter(event_time)\nORDER BY event_time"
    }
   ]
  },
  {
   "title": "Top 10 Used disk(GB)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  concat(node , disk) AS metric,\n  Used/1024/1024/1024\nFROM server_disk\nWHERE\n  $__timeFilter(event_time)\nORDER BY Used desc\n\n"
    }
   ]
  },
  {
   "title": "Server disk(used percent)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  concat(node , disk) AS metric,\n  used_percent\nFROM server_disk\nWHERE\n  $__timeFilter(event_time)\nORDER BY event_time"
    }
   ]
  },
  {
   "title": "Top 10 Server disk(used percent)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(event_time) AS \"time\",\n  concat(node , disk) AS metric,\n  used_percent\nFROM server_disk\nWHERE\n  $__timeFilter(event_time)\nORDER BY used_percent desc"
    }
   ]
  }
 ]
}